# Generated by Django 3.1.3 on 2020-12-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('is_main', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cheff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='upload')),
                ('last_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('mini_description', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('facebook', models.CharField(blank=True, max_length=300)),
                ('whatsapp', models.CharField(blank=True, max_length=300)),
                ('twitter', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Informaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('baker_info', models.CharField(max_length=300)),
                ('footer_info', models.CharField(max_length=300)),
                ('contact_info', models.CharField(max_length=300)),
                ('about_info', models.CharField(max_length=300)),
                ('card_info', models.ImageField(upload_to='upload')),
                ('time_info', models.CharField(max_length=300)),
                ('facebook_info', models.CharField(max_length=300)),
                ('instagram_info', models.CharField(max_length=300)),
                ('twitter_info', models.CharField(max_length=300)),
                ('shipping', models.CharField(max_length=300)),
                ('order_info', models.CharField(max_length=300)),
                ('payments_info', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
                ('status', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='upload')),
                ('rating', models.IntegerField(default=0)),
                ('last_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=600)),
                ('status', models.IntegerField(default=0)),
                ('is_main', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='upload')),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='upload')),
                ('old_price', models.FloatField(max_length=300)),
                ('new_price', models.FloatField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('photo2', models.ImageField(upload_to='upload')),
                ('tags', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
