# Generated by Django 3.1.3 on 2020-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='background',
            field=models.ImageField(default='default background', upload_to='upload'),
            preserve_default=False,
        ),
    ]
