# Generated by Django 3.1.3 on 2020-12-15 12:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201213_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('baker_info', models.CharField(max_length=300)),
                ('footer_info', models.CharField(max_length=300)),
                ('contact_info', models.CharField(max_length=300)),
                ('about_info', models.CharField(max_length=300)),
                ('card_info', models.ImageField(upload_to='upload')),
                ('time_info', models.CharField(max_length=300)),
                ('facebook_info', models.CharField(max_length=300)),
                ('instagram_info', models.CharField(max_length=300)),
                ('twitter_info', models.CharField(max_length=300)),
                ('shipping', models.CharField(max_length=300)),
                ('order_info', models.CharField(max_length=300)),
                ('payments_info', models.CharField(max_length=300)),
                ('reviews_foto', models.ImageField(blank=True, upload_to='upload')),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Informaton',
        ),
        migrations.RemoveField(
            model_name='review',
            name='background',
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
