# Generated by Django 3.1.3 on 2020-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201217_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='payments_info',
            new_name='date_info',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='twitter_info',
            new_name='design_by',
        ),
        migrations.AddField(
            model_name='information',
            name='footer_photo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='information',
            name='phone_info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='whatsapp_info',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
