# Generated by Django 3.1.3 on 2020-12-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201221_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='app_store',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
