# Generated by Django 3.1.3 on 2020-12-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_information_app_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='shipping',
        ),
    ]
