# Generated by Django 3.1.3 on 2020-12-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_information_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='order_info1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='order_info2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='order_info3',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
