# Generated by Django 3.1.3 on 2020-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201221_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='card_info1',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='information',
            name='card_info2',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='information',
            name='card_info3',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
