# Generated by Django 3.1.3 on 2020-12-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201221_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=300)),
                ('mini_description', models.CharField(blank=True, max_length=300)),
                ('cheff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cheff')),
            ],
        ),
    ]
