# Generated by Django 3.1.3 on 2020-12-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheff',
            name='signature',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
